@startuml MonsterTradingCardGame
package Models <<Folder>>{
    class User{
        + Username : string
        + Password : string
        + Token : string
        - _Stack : List<Card>
        - _Deck : List<Card>
    }
    class Card{
        + <<readonly>> Type : Type
        + <<readonly>> Name : string
        + <<readonly>> Damage : int
    }
    enum Type{
        Fire
        Water
        Normal
    }
    class MonsterCard{

    }
    class SpellCard{

    }
    class WaterSpell{

    }
    class FireSpell{
        
    }
    class NormalSpell{
        
    }
    class Goblin{

    }
    class Dragon{
        
    }
    class Wizzard{
        
    }
    class Ork{
        
    }
    class Knight{
        
    }
    class Kraken{
        
    }
    class Elve{
        
    }
    Card o-- Type

    Card <|-- MonsterCard
    Card <|-- SpellCard

    SpellCard <|-- WaterSpell
    SpellCard <|-- FireSpell
    SpellCard <|-- NormalSpell

    MonsterCard <|-- Goblin
    MonsterCard <|-- Dragon
    MonsterCard <|-- Wizzard
    MonsterCard <|-- Ork
    MonsterCard <|-- Kraken
    MonsterCard <|-- Elve
    MonsterCard <|-- Knight
}

package BLL <<Folder>>{

}

package DAL <<Folder>>{
    
}

@enduml